Lemon sqeeze integration
academykit/academykit pull request #30
Opened 2024-08-20 10:52 UTC by sailesh-lab

2024-08-21 03:33 UTC, ChanKamWo commented on AcademyKit.Server/Application/Common/Models/ResponseModels/LicenseResponseModel.cs
> +
namespace is missing

2024-08-21 03:35 UTC, ChanKamWo commented on AcademyKit.Server/Application/Common/Models/ResponseModels/LicenseResponseModel.cs
> +    [JsonProperty("id")]
To keep consistency, it might be better to remove JsonProperty attribute and use camelCase in JSON instead, like how we did in other entities.

2024-08-21 03:36 UTC, ChanKamWo commented on AcademyKit.Server/Infrastructure/Persistence/Migrations/20240816095318_License Table.cs
It might be better we leave no whitespace in the file name.

2024-08-21 03:37 UTC, ChanKamWo commented on README.md
Not necessary to update README

2024-08-21 03:38 UTC, ChanKamWo commented on academykit.client/src/Components/LemonSqueeze/useLemonSqueeze.tsx
It's not used.

2024-08-21 03:39 UTC, ChanKamWo commented on academykit.client/src/Components/LicenseForm.tsx
> +                "https://academykit.lemonsqueezy.com/buy/f83cb9f6-13d5-42f2-9a00-4ac5324e5cf6",
It might be better not to hardcode ID, but pull it from config

2024-08-21 03:43 UTC, ChanKamWo commented on academykit.client/vite.config.ts.timestamp-1723806411700-a8ef224c97614.mjs
I don't think it's necessary to commit this.

2024-08-21 03:48 UTC, ChanKamWo commented on academykit.client/src/context/LicenseContext.tsx
Upon login there are a few `/api/LemonSqueezy/validate?licenseKey=` request made. Why do we call it when we don't have licenseKey at all? Do we have to call it at intervals?

![image](https://github.com/user-attachments/assets/f373c935-ecab-459c-86af-14a75632bb22)

2024-08-21 03:50 UTC, ChanKamWo commented on AcademyKit.Server/Api/Controllers/LemonSqueezyController.cs
> +                request.AddQueryParameter("instance_name", "Academykit");
Would it be better to set this in appsettings?

2024-08-21 03:53 UTC, ChanKamWo commented on AcademyKit.Server/Application/Common/Interfaces/ILicenseService.cs
> +    Task AddLisence();
typo Lisence

2024-08-21 03:58 UTC, ChanKamWo commented on AcademyKit.Server/Application/Common/Models/ResponseModels/LicenseResponseModel.cs
Not required: Maybe extending from AuditableEntity/IdentifiableEntity to keep consistency could be better.

2024-08-21 03:59 UTC, ChanKamWo commented on AcademyKit.Server/Domain/Entities/License.cs
Use PascalCase in the properties.

2024-08-21 04:00 UTC, ChanKamWo commented on AcademyKit.Server/Infrastructure/Services/LicenseService.cs
Typo: Lisence

2024-08-21 04:02 UTC, ChanKamWo commented on AcademyKit.Server/Application/Common/Interfaces/ILicenseService.cs
Unused file

2024-08-21 04:02 UTC, ChanKamWo commented on AcademyKit.Server/Infrastructure/Services/LicenseService.cs
Unused

2024-08-21 04:04 UTC, ChanKamWo commented on academykit.client/src/Components/LicenseForm.tsx
> +      license_key: "",
use camelCase

2024-08-21 04:08 UTC, ChanKamWo commented on academykit.client/src/utils/constants.ts
> +export const License_Key = "licenseKey";
Naming convention is not followed

2024-08-21 04:10 UTC, ChanKamWo requested changes
Some issues must be resolved before merging.

2024-08-22 10:20 UTC, ChanKamWo commented on academykit.client/src/Components/LicenseForm.tsx
> +  // const license = useLicenseValidation();
remove commented code

2024-08-22 10:21 UTC, ChanKamWo commented on academykit.client/src/Components/LicenseForm.tsx
> +            {t("Buy Key")}
translation not found. please add it with consistent naming convention.

2024-08-22 10:24 UTC, ChanKamWo commented on AcademyKit.Server/Application/Common/Models/ResponseModels/LicenseResponseModel.cs
Please follow same naming convention(PascalCase) in the property names. and in the JSON object use camelCase naming convention in the property names.

2024-08-22 10:25 UTC, ChanKamWo commented on academykit.client/src/Components/LicenseForm.tsx
> +  const activateLicense = useActivatelicense();
useActivateLicense instead of useActivatelicense

2024-08-22 10:25 UTC, ChanKamWo commented on academykit.client/src/Components/LicenseForm.tsx
> +  // const license = useLicenseValidation();
please remove commented code

2024-08-22 11:37 UTC, ChanKamWo commented on AcademyKit.Server/Api/Controllers/LemonSqueezyController.cs
> +        public class LicenseResponse
Why do you define these entities here and in LicenseResponseModel?

2024-08-22 11:43 UTC, sailesh-lab commented on AcademyKit.Server/Application/Common/Models/ResponseModels/LicenseResponseModel.cs
This is the response from lemonSqueezy so we need to write it in its format.. In previous comment you have asked to remove the JsonProperty so I have removed it.

2024-08-22 11:48 UTC, sailesh-lab commented on AcademyKit.Server/Api/Controllers/LemonSqueezyController.cs
> +        public class LicenseResponse
I have removed now. LemonSqueezyResponseModel has added now instead of it and it is private.

2024-08-22 12:04 UTC, ChanKamWo requested changes
Now as I log into the app for the first time. I don't see the dialog for license key anymore.


https://github.com/user-attachments/assets/2bd9718f-be40-4c76-98b0-8c1161a12358

2024-08-22 12:18 UTC, ChanKamWo commented on AcademyKit.Server/Api/Controllers/LemonSqueezyController.cs
> +        public class LicenseResponse
Please define the entities in `AcademyKit.Server/Application/Common/Models/` or `AcademyKit.Server/Domain/Entities/` correspondingly. 

And use naming convention consistent to other existing files. Take this as example,

```cs
    public class LicenseResponseModel
    {
        [JsonProperty("activated")]
        public bool Activated { get; set; }

        [JsonProperty("valid")]
        public bool Valid { get; set; }

        [JsonProperty("error")]
        public string Error { get; set; }

        [JsonProperty("license_key")]
        public LicenseKey LicenseKey { get; set; }

        [JsonProperty("instance")]
        public object Instance { get; set; }

        [JsonProperty("meta")]
        public Meta Meta { get; set; }
    }
 ```
 
 Sorry, I see why you use JsonProperty in the first revision now.

2024-08-22 12:21 UTC, ChanKamWo commented on academykit.client/src/utils/services/licenseService.ts
> +  return useMutation({
We should use useQuery, right?

2024-08-22 13:16 UTC, sailesh-lab commented on academykit.client/src/utils/services/licenseService.ts
> +  return useMutation({
It is get api but called when button is clicked. So, It is an action not an effect.

2024-08-23 11:47 UTC, ChanKamWo approved these changes

2024-08-23 11:54 UTC, merged