SSO Integration and Issue Fix#10
academykit/academykit pull request #31
Opened 2024-08-20 12:17 UTC by PramodVurilo

2024-08-21 02:44 UTC, ChanKamWo commented
@PramodVurilo please check 
![image](https://github.com/user-attachments/assets/9185cfc2-db31-4678-8354-3c056a9b255a)

Also, did you push all the changes? Are we expected to see some login options in UI
![image](https://github.com/user-attachments/assets/82779839-727d-465a-ba8b-27564749494d)

2024-08-21 10:38 UTC, PramodVurilo commented
> @PramodVurilo please check ![image](https://private-user-images.githubusercontent.com/4598905/359728412-9185cfc2-db31-4678-8354-3c056a9b255a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzY5NDQsIm5iZiI6MTcyNDIzNjY0NCwicGF0aCI6Ii80NTk4OTA1LzM1OTcyODQxMi05MTg1Y2ZjMi1kYjMxLTQ2NzgtODM1NC0zYzA1NmE5YjI1NWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMTAzNzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmYzODRjODkwZGRlZmZkZjJhMDQ4ZGYwZTczYmRiMjYxYWRmNmUzM2Q3NGExNDdiOGFmYWJiMGUzZGIxMGJmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eZgiA0vpmkKpQ-gtpI0FDzPli7D_3rwXnNGALE6KRQg)
> 
> Also, did you push all the changes? Are we expected to see some login options in UI ![image](https://private-user-images.githubusercontent.com/4598905/359728806-82779839-727d-465a-ba8b-27564749494d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzY5NDQsIm5iZiI6MTcyNDIzNjY0NCwicGF0aCI6Ii80NTk4OTA1LzM1OTcyODgwNi04Mjc3OTgzOS03MjdkLTQ2NWEtYmE4Yi0yNzU2NDc0OTQ5NGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMTAzNzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjkzYTZiYmQ3MDQzZjMxNzhkOGJlYTM4NDc3ZmZhYzFhMzcyMDE5ZmRmMmE1YWU0NzU1NzA2ZTBmM2Y1OGY4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cjDOtEe-e5s1c8GqSzo02JQ3D0S2-P1OvxgsYXKI1a4)

Forntend implemention is not done yet.

2024-08-22 13:15 UTC, ChanKamWo commented on AcademyKit.Server/Application/Common/Models/ResponseModels/OAuthTokenResponse.cs
Please follow C# naming convension in property names. use PascalCase

2024-08-22 13:16 UTC, ChanKamWo commented on AcademyKit.Server/Infrastructure/Persistence/Migrations/20240816074649_isDefault col added in Group.cs
Class name should be in PascalCase

2024-08-22 13:19 UTC, ChanKamWo commented on AcademyKit.Server/Api/Controllers/AccountController.cs
> +            var nonce = "Q2k4UWFtMmZ1NjlBNG1oRU1ENnNNRGhx";
Should nonce be generated on each call instead of hardcode?

2024-08-22 13:21 UTC, ChanKamWo requested changes
Some issues must be addressed before merging.

2024-08-23 12:22 UTC, ChanKamWo commented on AcademyKit.Server/Api/Controllers/AccountController.cs
> +                + $"nonce={CommonHelper.GenerateNonce}&"
not a function call.

2024-08-23 12:22 UTC, ChanKamWo commented on AcademyKit.Server/Api/Controllers/AccountController.cs
> +                + $"nonce={CommonHelper.GenerateNonce}";
not a function call

2024-08-23 12:26 UTC, ChanKamWo commented on AcademyKit.Server/Application/Common/Models/ResponseModels/OAuthTokenResponse.cs
Please follow PascalCase property naming convention. You can use `JsonProperty` attribute.

2024-08-23 12:27 UTC, ChanKamWo commented on AcademyKit.Server/Infrastructure/Persistence/Migrations/20240816074649_isDefault col added in Group.cs
File name should follow PascalCase naming convention. with no whitespaces.

2024-08-23 12:29 UTC, ChanKamWo requested changes
Please merge main branch and fix the required issues.

2024-09-01 07:11 UTC, closed without merging