feat: SSO integration
academykit/academykit pull request #39
Opened 2024-08-27 14:54 UTC by sailesh-lab

2024-08-28 06:29 UTC, sursaone requested changes

2024-08-28 06:29 UTC, sursaone commented on AcademyKit.Server/Api/Controllers/AccountController.cs
> +                return StatusCode(
Since this is redirect based response returning this result won't work

2024-08-28 06:29 UTC, sursaone commented on AcademyKit.Server/Api/Controllers/AccountController.cs
> +            var nonce = CommonHelper.GenerateNonce();
validate first if SSO for Entra ID is configured or not

2024-08-28 06:29 UTC, sursaone commented on AcademyKit.Server/Api/Controllers/AccountController.cs
> +            var dicData = new Dictionary<string, string>
Validate before SSO is configured

2024-08-28 06:29 UTC, sursaone commented on AcademyKit.Server/Api/Controllers/AccountController.cs
> +                {
Since this is redirect based response returning this result won't work

2024-08-28 06:29 UTC, sursaone commented on AcademyKit.Server/Api/Controllers/AccountController.cs
> +                return StatusCode(
Since this is redirect based response returning this result won't work

2024-08-28 06:29 UTC, sursaone commented on AcademyKit.Server/Application/Common/Models/ResponseModels/EmailResponseModel.cs
> +        [JsonProperty("mail")]
Since property name and json property name are same no need to have JSONProperty

2024-08-28 06:29 UTC, sursaone commented on AcademyKit.Server/Infrastructure/Configurations/ConfigurationExtension.cs
> -                            throw new AuthenticationFailureException(
Shouldn't be removed

2024-08-28 06:29 UTC, sursaone commented on AcademyKit.Server/Infrastructure/Configurations/Microsoft.cs
> +        public string RedirectUri { get; set; }
only client Id and secret should be configurable

2024-08-28 06:40 UTC, sursabipul commented on AcademyKit.Server/Application/Common/Models/ResponseModels/OAuthTokenResponse.cs
> +        public string Access_token { get; set; }
use Pascal Case for property name
and use JsonProperty for such case

2024-09-01 06:15 UTC, sursaone approved these changes

2024-09-01 06:16 UTC, merged